/**
 * Rules the client and the server must agree on, defined once. The client
 * validates with the same definitions the server enforces, so it cannot
 * accept a name the server then rejects, or build a link the server refuses.
 */

export const MAX_PARTICIPANTS = 30;
export const MAX_NAME_LENGTH = 32;

/** Room ids: 11 base64url characters, 64 random bits generated by the server. */
export const ROOM_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/;

/**
 * Participant ids as clients see them: 16 base64url characters, derived by
 * the server from the room and the session token (ADR 0006).
 */
export const PARTICIPANT_ID_PATTERN = /^[A-Za-z0-9_-]{16}$/;

/**
 * At most one nudge per person every 30 seconds, whoever sends it (ADR
 * 0007). Shared, because the client's "Nudged" button stays disabled for
 * exactly this long: with its own copy, one side could change and the
 * button would come back while the server still drops the nudge.
 */
export const NUDGE_COOLDOWN_MS = 30_000;

/**
 * The winning rule sets one vote aside at each end, the lowest and the
 * highest, only from this many numeric votes on (docs/design.md, The
 * winning card). With two or three there is too little to set aside: 13,
 * 13, 5 would lose a 13 and have no result. Shared, because the client
 * explains a reveal with no result by which rule applied.
 */
export const DROP_ENDS_FROM = 4;

/**
 * The ticket being estimated (the room's "Now estimating"): at most this many
 * characters once cleaned, in UTF-16 code units like names, which is also how
 * the input's maxlength counts.
 */
export const MAX_TICKET_LENGTH = 120;

/**
 * The raw text's cap on the wire, a payload-sanity limit like the name's
 * 200: pasted text with runs of spaces may clean down to 120, but nothing
 * longer than this is read at all.
 */
export const MAX_TICKET_INPUT = 200;

/**
 * A ticket as the room shows it, or null for none. Runs of whitespace,
 * newlines and tabs included, become one space first, so a pasted line break
 * separates words rather than joining them; then any other control character
 * goes, and the spaces that were either side of it collapse again, so no
 * double space is left; then the ends are trimmed. Empty means no ticket. Length is checked by
 * the caller, against MAX_TICKET_LENGTH.
 */
export function cleanTicket(raw: string): string | null {
  const cleaned = raw
    .replace(/\s+/g, " ")
    .replace(/\p{Cc}/gu, "")
    .replace(/ {2,}/g, " ")
    .trim();
  return cleaned === "" ? null : cleaned;
}

/**
 * The timer (ADR 0008). A duration is whole seconds from 10 s to 10 min; the
 * default is a minute, and the presets are what the facilitator's select
 * offers before Custom. +30 s never takes what is left past the maximum.
 */
export const TIMER_DEFAULT_MS = 60_000;
export const TIMER_MIN_MS = 10_000;
export const TIMER_MAX_MS = 600_000;
export const TIMER_ADD_MS = 30_000;
export const TIMER_PRESETS_MS = [30_000, 60_000, 120_000, 180_000, 300_000];

/** Whether `ms` is a duration the timer accepts. */
export function validDuration(ms: number): boolean {
  return (
    Number.isInteger(ms) &&
    ms % 1_000 === 0 &&
    ms >= TIMER_MIN_MS &&
    ms <= TIMER_MAX_MS
  );
}

/** Session tokens: 22–64 url-safe characters covers a randomUUID without over-fitting. */
export const SESSION_TOKEN_PATTERN = /^[A-Za-z0-9_-]{22,64}$/;

/**
 * Trims the ends and collapses internal runs of spaces, tabs and newlines to
 * one space, so a pasted name cannot break the participant list.
 */
export function normaliseName(raw: string): string {
  return raw.trim().replace(/\s+/g, " ");
}

/**
 * The normalised name if it is valid, otherwise null. Length is measured in
 * UTF-16 code units, so an emoji counts as two: a known, accepted
 * simplification.
 */
export function validName(raw: string): string | null {
  const name = normaliseName(raw);
  return name.length > 0 && name.length <= MAX_NAME_LENGTH ? name : null;
}
