/**
 * Rules the client and the server must agree on, defined once. The client
 * validates with the same definitions the server enforces, so it cannot
 * accept a name the server then rejects, or build a link the server refuses.
 */

export const MAX_PARTICIPANTS = 30;
export const MAX_NAME_LENGTH = 32;

/** Room ids: 11 base64url characters, 64 random bits generated by the server. */
export const ROOM_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/;

/**
 * Participant ids as clients see them: 16 base64url characters, derived by
 * the server from the room and the session token (ADR 0006).
 */
export const PARTICIPANT_ID_PATTERN = /^[A-Za-z0-9_-]{16}$/;

/** Session tokens: 22–64 url-safe characters covers a randomUUID without over-fitting. */
export const SESSION_TOKEN_PATTERN = /^[A-Za-z0-9_-]{22,64}$/;

/**
 * Trims the ends and collapses internal runs of spaces, tabs and newlines to
 * one space, so a pasted name cannot break the participant list.
 */
export function normaliseName(raw: string): string {
  return raw.trim().replace(/\s+/g, " ");
}

/**
 * The normalised name if it is valid, otherwise null. Length is measured in
 * UTF-16 code units, so an emoji counts as two: a known, accepted
 * simplification.
 */
export function validName(raw: string): string | null {
  const name = normaliseName(raw);
  return name.length > 0 && name.length <= MAX_NAME_LENGTH ? name : null;
}
